#ifndef EXPRESSION_TYPE_H
#define EXPRESSION_TYPE_H

typedef enum ExpressionType {
	LITERAL_EXPRESSION,
	IDENTIFIER_EXPRESSION,
	UNARY_EXPRESSION,
	BINARY_EXPRESSION
} ExpressionType;

#endif // EXPRESSION_TYPE_H