#ifndef STATEMENT_TYPE_H
#define STATEMENT_TYPE_H

typedef enum {
	LOOP_STATEMENT,
	WHILE_STATEMENT,
	CONDITIONAL_STATEMENT,
	SCOPE_STATEMENT,
	DECLARATION_STATEMENT,
	ASSIGNMENT_STATEMENT,
	OUTPUT_STATEMENT,
	INPUT_STATEMENT
} StatementType;

char *get_statement_type_as_string(StatementType type);

#endif // STATEMENT_TYPE_H