#ifndef STATEMENT_TYPE_H
#define STATEMENT_TYPE_H

typedef enum {
	WHILE_STATEMENT,
	CONDITIONAL_STATEMENT,
	SCOPE_STATEMENT,
	DECLARATION_STATEMENT,
	ASSIGNMENT_STATEMENT,
	OUTPUT_STATEMENT,
	INPUT_STATEMENT
} StatementType;

#endif // STATEMENT_TYPE_H